import mongoose from "mongoose";

const customerSchema = new mongoose.Schema({
  id: String,
  duration: String,
  emiAmount: Number,
  paymentTerms: String,
  marketerName: String,
  email: String,
  pincode: String,
  state: String,
  city: String,
  phone: String,
  dob: String,
  gender: String,
  address: String,
  name: String,
  marketatName: String,
  referenceId: String,
  projectId: { type: mongoose.Schema.Types.ObjectId, ref: 'Project' },

  cedId: {type: mongoose.Schema.Types.ObjectId,ref: "MarketingHead"},
  ddId: {type: mongoose.Schema.Types.ObjectId,ref: "MarketingHead"},
  introducerId: {type: mongoose.Schema.Types.ObjectId,ref: "MarketingHead"},
  marketerDetailId: {type: mongoose.Schema.Types.ObjectId,ref: "MarketDetail"},
  nomineeName: String,
  nomineeAge: String,
  nomineeRelationship:String ,
  nameOfGuardian:String ,
  so_wf_do:String ,
  relationshipWithCustomer:String ,
  guardianAddress: String,

  plotNo: String,
  projectArea: String,
  nationality: String,
  landLineNo: String,
  occupation: String,
  qualification: String,
  planNo: String,
  communicationAddress: String,
  fatherOrHusbandName: String,
  motherName: String,
  immSupervisorName: String,
  photoUrl: String,

  oldData: {type:Boolean, default:false},
  marketerPercent: String,
  marketerId: String,
}, { timestamps: true });

export const Customer = mongoose.model("Customer", customerSchema);
